apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
spec:
  refreshInterval: "30m"
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /qat/ap-southeast-1/my-app/database-url
    - secretKey: API_KEY
      remoteRef:
        key: /qat/ap-southeast-1/my-app/api-key
